export {TwentyFortyEight} from './2048';
export {Admin} from './Admin';
export {FlashCards} from './FlashCards';
export {Home} from './Home';
export {Memory} from './Memory';
export {PopQuiz} from './PopQuiz';
export {Profile} from './Profile';
export {ToneTrainer} from './ToneTrainer';
export {Uno} from './Uno';